name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        
    - name: DockerHub login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Inciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"


    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version.output.version }}
      run: |
        docker build -t fefochico/docker-graphql:$NEW_VERSION .
        docker build -t fefochico/docker-graphql:latest .
        
    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version.output.version }}
      run: |
        docker push fefochico/docker-graphql:NEW_VERSION
        docker push fefochico/docker-graphql:latest
        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
